### ISSUE TITLE
Symlink not working with Windows

### ISSUE THREAD

**Issue by yb6599** [Jacob-Stevens-Haas/mitosis#18]
While trying to run experiments on Windows, the log file gives the following error.
```
nohup: ignoring input
trial entry: insert--plot2-duration-absnoise-duration-absnoise-all-4nonzero-cubic-test-absrel5-19-kalman-auto3-duration-noise--2--00104fe63791460a926268ce48c033c4cb896c30------None
Running experiment gridsearch, simulation variant plot2-duration-absnoise-duration-absnoise-all-4nonzero-cubic-test-absrel5-19-kalman-auto3-duration-noise, iteration 2 at time: 2024-01-02 16:27:53 UTC.  Current repo hash: 00104fe63791460a926268ce48c033c4cb896c30
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Finished experiment at time: 2024-01-02 16:27:57 UTC.  Results: None
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\UW\Research\gen-experiments\env\Scripts\mitosis.exe\__main__.py", line 4, in <module>
    from mitosis.__main__ import main
  File "D:\UW\Research\gen-experiments\env\Lib\site-packages\mitosis\__main__.py", line 113, in <module>
    main()
  File "D:\UW\Research\gen-experiments\env\Lib\site-packages\mitosis\__main__.py", line 110, in main
    run(**kwargs)
  File "D:\UW\Research\gen-experiments\env\Lib\site-packages\mitosis\__init__.py", line 386, in run
    (exp_metadata_folder / "experiment").symlink_to(trials_folder / new_filename)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 1198, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] A required privilege is not held by the client: 'D:\\UW\\Research\\gen-experiments\\src\\gen_experiments\\trials\\trial_gridsearch_cubic_ho_plot2-duration-absnoise-duration-absnoise-all-4nonzero-cubic-test-absrel5-19-kalman-auto3-duration-noise_2_433eb8.html' -> 'D:\\UW\\Research\\gen-experiments\\src\\gen_experiments\\trials\\2024-01-02_433eb8\\experiment'
Installed kernelspec 3473608395585562627634549 in C:\Users\bhang\AppData\Roaming\jupyter\kernels\3473608395585562627634549
```

**Comment by Jacob-Stevens-Haas** [comment]
Yash I know we talked about this on the call today but could you amplify this issue so we remember the info when we come back to it later?  I.e. what is the command you used, and did you find anything about how to enable this permission on windows?
